apiVersion: v1
items:
  - apiVersion: manageables.dorosoft.de/v1alpha1
    kind: Project
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"manageables.dorosoft.de/v1alpha1","kind":"Project","metadata":{"annotations":{},"labels":{"app.kubernetes.io/created-by":"manager","app.kubernetes.io/instance":"project-sample","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"project","app.kubernetes.io/part-of":"manager"},"name":"project-sample","namespace":"websites-dev"},"spec":{"company":"Bunderdruckereis","job":"DevOps Consultant","neededSkills":[{"experience":"5y","name":"Kubernetes"},{"experience":"1y","name":"AWS"}],"openPositions":5}}
      creationTimestamp: "2024-02-15T19:02:46Z"
      generation: 1
      labels:
        app.kubernetes.io/created-by: manager
        app.kubernetes.io/instance: project-sample
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: project
        app.kubernetes.io/part-of: manager
      name: project-sample
      namespace: websites-dev
      resourceVersion: "502930"
      uid: 29596aca-ee71-49b1-933a-1767eb72827c
    spec:
      company: Bunderdruckereis
      job: DevOps Consultant
      neededSkills:
        - experience: 5y
          name: Kubernetes
        - experience: 1y
          name: AWS
      openPositions: 5
    status:
      possiblePeople:
        - percentageStrict: "50.00"
          percentageWithoutAlternatives: "0.00"
          percentageWithoutExperience: "50.00"
          personName: dominik.robert
          skills:
            - fulfilled: true
              skillAvailable: true
              skillSpecs:
                experience: 5y
                name: Kubernetes
            - skillSpecs:
                experience: 1y
                name: AWS
kind: List
metadata:
  resourceVersion: ""
