# permissions for end users to view projekts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: projekt-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: manager
    app.kubernetes.io/part-of: manager
    app.kubernetes.io/managed-by: kustomize
  name: projekt-viewer-role
rules:
- apiGroups:
  - manageables.dorosoft.de
  resources:
  - projekts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manageables.dorosoft.de
  resources:
  - projekts/status
  verbs:
  - get
