# permissions for end users to edit skills.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: skill-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: manager
    app.kubernetes.io/part-of: manager
    app.kubernetes.io/managed-by: kustomize
  name: skill-editor-role
rules:
- apiGroups:
  - manageables.dorosoft.de
  resources:
  - skills
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manageables.dorosoft.de
  resources:
  - skills/status
  verbs:
  - get
